[package]
name = "everygarf"
version = "2.0.0"
edition = "2021"
authors = ["darcy"]

[dependencies]
clap = { version = "4.4.8", features = ["derive"] }
tokio = { version = "1.34.0", features = ["full"] }
futures = "0.3.29"
reqwest = "0.11.22"
image = "0.24.7"
bytes = "1.5.0"
chrono = "0.4.31"
dirs-next = "2.0.0"
humantime = "2.1.0"
